# Generated by Django 5.1.6 on 2025-03-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantusers',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
