# Generated by Django 5.1.6 on 2025-03-04 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tenantusers_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
