# Generated by Django 5.1.6 on 2025-03-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantusers',
            name='hasStaffPermission',
            field=models.BooleanField(default=False),
        ),
    ]
