# Generated by Django 5.1.6 on 2025-03-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tenantusers_hasstaffpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantusers',
            name='hasBlogPermission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantusers',
            name='hasCommunityPermission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantusers',
            name='hasCoursesPermission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantusers',
            name='hasNewsletterPermission',
            field=models.BooleanField(default=False),
        ),
    ]
