# Generated by Django 5.1.6 on 2025-03-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tenantusers_hasblogpermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantusers',
            name='hasBuilderPermission',
            field=models.BooleanField(default=False),
        ),
    ]
