# Generated by Django 5.1.6 on 2025-04-01 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tenants'),
        ),
    ]
