apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: backend
build:
  artifacts:
    - image: joelthomas1103/adome-blog
      context: blog-service
      docker:
        dockerfile: Dockerfile
      
      sync:
        manual:
          - src: "**/*.py"
            dest: "/app"
          - src: "!**/consumer.py"
            dest: "/app"

    - image: joelthomas1103/adome-comment
      context: comment-service
      docker:
        dockerfile: Dockerfile
      
      sync:
        manual:
          - src: "**/*.py"
            dest: "/app"
          - src: "!**/consumer.py"
            dest: "/app"

    - image: joelthomas1103/adome-community
      context: community-service
      docker:
        dockerfile: Dockerfile
      
      sync:
        manual:
          - src: "**/*.py"
            dest: "/app"
          - src: "!**/consumer.py"
            dest: "/app"

    - image: joelthomas1103/adome-course
      context: course-service
      docker:
        dockerfile: Dockerfile
      
      sync:
        manual:
          - src: "**/*.py"
            dest: "/app"
          - src: "!**/consumer.py"
            dest: "/app"

    - image: joelthomas1103/adome-media
      context: media-service
      docker:
        dockerfile: Dockerfile
      
      sync:
        manual:
          - src: "**/*.py"
            dest: "/app"
          - src: "!**/consumer.py"
            dest: "/app"

    - image: joelthomas1103/adome-payment
      context: payment-service
      docker:
        dockerfile: Dockerfile
      
      sync:
        manual:
          - src: "**/*.py"
            dest: "/app"
          - src: "!**/consumer.py"
            dest: "/app"

    - image: joelthomas1103/adome-tenant
      context: tenant-service
      docker:
        dockerfile: Dockerfile
      
      sync:
        manual:
          - src: "**/*.py"
            dest: "/app"
          - src: "!**/consumer.py"
            dest: "/app"

    - image: joelthomas1103/adome-user
      context: user-service
      docker:
        dockerfile: Dockerfile
      
      sync:
        manual:
          - src: "**/*.py"
            dest: "/app"
          - src: "!**/consumer.py"
            dest: "/app"

    - image: joelthomas1103/adome-webbuilder
      context: website-builder
      docker:
        dockerfile: Dockerfile
      
      sync:
        manual:
          - src: "**/*.py"
            dest: "/app"
          - src: "!**/consumer.py"
            dest: "/app"

manifests:
  rawYaml:
    - ingress-websockets.txt
    - k8s/postgres-init-configmap.yml
    - k8s/deployments/blog-deployment.yaml
    - k8s/deployments/comment-deployment.yaml
    - k8s/deployments/community-deployment.yaml
    - k8s/deployments/course-deployment.yaml
    - k8s/deployments/media-deployment.yaml
    - k8s/deployments/payment-deployment.yaml
    - k8s/deployments/rabbitmq-deployment.yaml
    - k8s/deployments/redis-deployment.yaml
    - k8s/deployments/rootdb-deployment.yaml
    - k8s/deployments/tenant-deployment.yaml
    - k8s/deployments/user-deployment.yaml
    - k8s/deployments/webbuilder-deployment.yaml
    - k8s/ingress/development/ingress.yml
    - k8s/secrets/secret.yml
