apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: backend
build:
  artifacts:
    - image: joelthomas1103/blog
      context: blog-service
      docker:
        dockerfile: Dockerfile

      sync:
        manual:
          - src: "**/*.py"
            dest: "/app"
          - src: "!**/consumer.py"
            dest: "/app"


    - image: joelthomas1103/comment
      context: comment-service
      docker:
        dockerfile: Dockerfile


      sync:
        manual:
          - src: "**/*.py"
            dest: "/app"
          - src: "!**/consumer.py"
            dest: "/app"


    - image: joelthomas1103/course
      context: course-service
      docker:
        dockerfile: Dockerfile

        
      sync:
        manual:
          - src: "**/*.py"
            dest: "/app"
          - src: "!**/consumer.py"
            dest: "/app"


    - image: joelthomas1103/media
      context: media-service
      docker:
        dockerfile: Dockerfile

        
      sync:
        manual:
          - src: "**/*.py"
            dest: "/app"
          - src: "!**/consumer.py"
            dest: "/app"


    - image: joelthomas1103/payment
      context: payment-service
      docker:
        dockerfile: Dockerfile

        
      sync:
        manual:
          - src: "**/*.py"
            dest: "/app"
          - src: "!**/consumer.py"
            dest: "/app"


    - image: joelthomas1103/tenant
      context: tenant-service
      docker:
        dockerfile: Dockerfile

        
      sync:
        manual:
          - src: "**/*.py"
            dest: "/app"
          - src: "!**/consumer.py"
            dest: "/app"


    - image: joelthomas1103/user
      context: user-service
      docker:
        dockerfile: Dockerfile

        
      sync:
        manual:
          - src: "**/*.py"
            dest: "/app"
          - src: "!**/consumer.py"
            dest: "/app"


    - image: joelthomas1103/webbuilder
      context: website-builder
      docker:
        dockerfile: Dockerfile

        
      sync:
        manual:
          - src: "**/*.py"
            dest: "/app"
          - src: "!**/consumer.py"
            dest: "/app"


manifests:
  rawYaml:
    - k8s/postgres-init-configmap.yml
    - k8s/deployments/blog-deplment.yml
    - k8s/deployments/comments-deployment.yml
    - k8s/deployments/course-deployment.yml
    - k8s/deployments/db-deployment.yml
    - k8s/deployments/media-deployment.yml
    - k8s/deployments/payment-deployment.yml
    - k8s/deployments/rabbitmq-deployment.yml
    - k8s/deployments/tenant-deployment.yml
    - k8s/deployments/user-deployment.yml
    - k8s/deployments/webbuilder-deployment.yml
    - k8s/ingress/ingress.yml
    - k8s/secrets/secret.yml
