# Generated by Django 5.1.6 on 2025-04-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chapter_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
