# Generated by Django 5.1.6 on 2025-04-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_module_chapter_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='chapter',
            name='JsonContent',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='htmlContent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='JsonContent',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='htmlContent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
