# Generated by Django 5.1.6 on 2025-04-26 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_description_chapter_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='has_video',
        ),
    ]
