# Generated by Django 5.1.6 on 2025-05-01 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_chapter_has_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tenants')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tenantusers')),
            ],
        ),
    ]
