apiVersion: v1
kind: Secret
metadata:
  name: common-secret
type: Opaque
data:
  SECRET_KEY : 94Wsq1vCTpJkTxlr3mLK_rWWbJVqJHoJTTdJ1w_WJySHzsbKYUEY1mCc4sYiZri-W6wFVg3FKizDPDlQq0EgllbkScJ4xvh7XQmvZODcVto