# Generated by Django 5.1.6 on 2025-02-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usercache_is_active_logoimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logoimages',
            old_name='logo',
            new_name='file',
        ),
    ]
