# Generated by Django 5.1.6 on 2025-05-01 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tenantimagebucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantChapterVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='tenant_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tenants')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usercache')),
            ],
        ),
    ]
