# Generated by Django 5.1.6 on 2025-04-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usercache_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantusers',
            options={'verbose_name': 'Tenant User', 'verbose_name_plural': 'Tenant Users'},
        ),
        migrations.AlterUniqueTogether(
            name='tenantusers',
            unique_together={('tenant', 'user')},
        ),
    ]
