# Generated by Django 5.1.6 on 2025-04-26 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tenantusers_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('bank_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=100, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.tenants')),
            ],
        ),
    ]
