# Generated by Django 5.1.6 on 2025-04-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_tenantpayments_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpayments',
            name='encrypted_bank_account_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantpayments',
            name='encrypted_bank_ifsc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantpayments',
            name='encrypted_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantpayments',
            name='encrypted_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantpayments',
            name='encrypted_pan_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
