# Generated by Django 5.1.6 on 2025-04-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tenantpayments_encrypted_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpayments',
            name='encrypted_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
