# Generated by Django 5.1.6 on 2025-04-30 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tenantpayments_encrypted_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=255)),
                ('order_product', models.CharField(max_length=100)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('order_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('order_signature', models.CharField(blank=True, max_length=256, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('order_status', models.CharField(default='created', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_time', models.DateTimeField(blank=True, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.tenants')),
            ],
        ),
    ]
