# Generated by Django 5.1.6 on 2025-04-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_tenantwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
    ]
