# Generated by Django 5.1.6 on 2025-04-30 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_coursecache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coursecache'),
        ),
    ]
