# Generated by Django 5.1.6 on 2025-04-30 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tenantusers'),
        ),
    ]
