# Generated by Django 5.1.6 on 2025-05-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_course_id_order_course_remove_order_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecache',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
