# Generated by Django 5.1.6 on 2025-05-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_coursecache_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
