# Generated by Django 5.1.6 on 2025-05-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_order_payment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantpayments',
            name='encrypted_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
