# Generated by Django 5.1.6 on 2025-05-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('1', 'Free'), ('2', 'Premium')], default='1', max_length=10),
        ),
    ]
