apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
data:
  init.sql: |
    CREATE DATABASE user_service;
    CREATE DATABASE tenants_service;
    CREATE DATABASE media-service;
    CREATE DATABASE payment-service;
