# Generated by Django 5.1.6 on 2025-05-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_community_communitychats_communitymembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitychats',
            name='link',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
