# Generated by Django 5.1.6 on 2025-05-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_communitychats_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitychats',
            name='optimistic_uui',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
