# Generated by Django 5.1.6 on 2025-05-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_optimistic_uui_communitychats_optimistic_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitychats',
            name='optimistic_uuid',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
