# Generated by Django 5.1.6 on 2025-02-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercache',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
