# Generated by Django 5.1.6 on 2025-02-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_tenants_founding_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenants',
            name='courses',
            field=models.BooleanField(default=False),
        ),
    ]
