# Generated by Django 5.1.6 on 2025-05-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenants',
            name='domain',
        ),
    ]
