apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant
  template:
    metadata:
      labels:
        app: tenant
    spec:
      initContainers:
        - name: wait-for-rootdb
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z rootdb 5432; do echo "Waiting for rootdb..."; sleep 2; done']

        - name: wait-for-rabbitmq
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo "Waiting for rabbitmq..."; sleep 2; done']
      
      containers:
        - name: tenant
          image: joelthomas1103/tenant:latest 
          ports:
            - containerPort: 8000  
          env:
            - name: DB_HOST
              value: "rootdb"  
            - name: DB_NAME
              value: "root"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "root"
          volumeMounts:
            - name: tenant-storage
              mountPath: /app/tenant_data/  
      
      volumes:
        - name: tenant-storage
          persistentVolumeClaim:
            claimName: shared-migrations-pvc 

---
apiVersion: v1
kind: Service
metadata:
  name: tenant-service
spec:
  selector:
    app: tenant  
  ports:
    - protocol: TCP
      port: 8000          
      targetPort: 8000    
  type: ClusterIP       