# userdb-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rootdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard