apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-migrations-pvc
spec:
  accessModes:
    - ReadWriteMany  
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  
