name: deploy-infra

on:
  push:
    branches:
      - main
    paths:
      - "k8s/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: adome
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Debug KUBE_CONFIG (optional, for troubleshooting)
      - name: Debug KUBE_CONFIG
        run: |
          echo "KUBE_CONFIG length: $(echo -n ${{ secrets.KUBE_CONFIG }} | wc -c)"
        continue-on-error: true

      # Set up kubeconfig for K3s cluster
      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig.yaml
          kubectl get nodes # Verify cluster access

      # Apply infrastructure manifests
      - name: Deploy infrastructure to K3s
        run: |
          kubectl apply -f k8s/secrets/secret.yml
          kubectl apply -f k8s/pvc/
          kubectl apply -f k8s/deployments/rabbitmq-deployment.yml
          kubectl apply -f k8s/deployments/redis-deployment.yml
          kubectl apply -f k8s/deployments/postgres-deployment.yml
        env:
          KUBECONFIG: $GITHUB_WORKSPACE/kubeconfig.yaml