name: deploy-user
on:
  push:
    branches: [main]
    paths:
      - 'user-service/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: adome
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create env
        working-directory: ./user-service
        run: |
          echo "DB_HOST=rootdb" >> .env
          echo "DB_NAME=root" >> .env
          echo "DB_USER=root" >> .env
          echo "DB_PASSWORD=root" >> .env
          echo "FRONTEND_URL=${{ secrets.FRONT_END }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          cat .env  # Debug: Verify env variables
      - name: Build and push Docker image
        working-directory: ./user-service
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t joelthomas1103/adome-user:${IMAGE_TAG} -t joelthomas1103/adome-user:latest .
          docker push joelthomas1103/adome-user:${IMAGE_TAG}
          docker push joelthomas1103/adome-user:latest
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Configure kubectl
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: adome-cluster
          location: asia-south1-a
          project_id: adome-ms
      - name: Update deployment with new image
        run: |
          kubectl set image deployment/user user=joelthomas1103/adome-user:${{ github.sha }}
          kubectl rollout restart deployment user
          kubectl rollout status deployment user