# Generated by Django 5.1.6 on 2025-04-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_website_created_at_website_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
