# Generated by Django 5.1.6 on 2025-04-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_website_is_default_website_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='web_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
